apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data
  namespace: umas
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: umas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
