apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  namespace: panoptes
  labels:
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/part-of: panoptes
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx-gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
