apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: panoptes
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: panoptes
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: loki
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
      name: http
