apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: umas
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: umas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
