apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: umas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-7.4-latest
          ports:
            - containerPort: 10051
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgres
            - name: POSTGRES_DB
              value: zabbix
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: umas-secrets
                  key: ZABBIX_DB_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 10051
            initialDelaySeconds: 60
          readinessProbe:
            tcpSocket:
              port: 10051
            initialDelaySeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
