apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: umas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:alpine-7.4-latest
          ports:
            - containerPort: 8080
          env:
            - name: ZBX_SERVER_HOST
              value: zabbix-server
            - name: DB_SERVER_HOST
              value: zabbix-postgres
            - name: POSTGRES_DB
              value: zabbix
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: umas-secrets
                  key: ZABBIX_DB_PASSWORD
            - name: PHP_TZ
              value: Asia/Baku
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
